# Generated by Django 5.2.1 on 2025-05-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem_set',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_name', models.CharField(blank=True, max_length=50, unique=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('topics', models.TextField()),
            ],
        ),
    ]
