# Generated by Django 5.2.1 on 2025-05-18 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_remove_problem_set_problem_id_problem_set_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('input_problem', models.CharField(blank=True, max_length=50)),
                ('output_problem', models.CharField(blank=True, max_length=50)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_id', to='problems.problem_set')),
            ],
        ),
    ]
